//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pantry_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public int IngredientsID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Quanity { get; set; }
        public string MeasurementID { get; set; }
        public string UserID { get; set; }
    }
}
