//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pantry_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurements
    {
        public int MeasurementID { get; set; }
        public string Cup { get; set; }
        public string Ounce { get; set; }
        public string Pound { get; set; }
        public string TableSpoon { get; set; }
        public string IngredientsID { get; set; }
        public string RecipesID { get; set; }
    
        public virtual Ingredients Ingredient { get; set; }
        public virtual Recipes Recipe { get; set; }
    }
}
