//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pantry_app.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PantryWise1Entities : DbContext
    {
        public PantryWise1Entities()
            : base("name=PantryWise1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PantryWiseUser> PantryWiseUsers { get; set; }
        public virtual DbSet<Security> Securities { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Ingredients> Ingredients { get; set; }
        public virtual DbSet<Measurements> Measurements { get; set; }
        public virtual DbSet<Recipes> Recipes { get; set; }
    }
}
