//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pantry_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PantryWiseUser_has_Inventory
    {
        public int UserID { get; set; }
        public string InventoryID { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual PantryWiseUser PantryWiseUser { get; set; }
    }
}
