//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pantry_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public int RecipesID { get; set; }
        public string RecipeName { get; set; }
        public string Decription { get; set; }
        public string InventoryID { get; set; }
        public string UserID { get; set; }
        public string MeasurementID { get; set; }
    }
}
